"""creacion de tercero

Revision ID: 23ba0e8a25b6
Revises: 881469009cc5
Create Date: 2025-03-26 07:30:41.758242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23ba0e8a25b6'
down_revision: Union[str, None] = '881469009cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    """Upgrade schema."""
    # globals()["upgrade_%s" % engine_name]()
    upgrade_engine1()


def downgrade(engine_name: str) -> None:
    """Downgrade schema."""
    # globals()["downgrade_%s" % engine_name]()
    downgrade_engine1()





def upgrade_engine1() -> None:
    """Upgrade engine1 schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tercero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_tercero_id'), 'tercero', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade_engine1() -> None:
    """Downgrade engine1 schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tercero_id'), table_name='tercero')
    op.drop_table('tercero')
    # ### end Alembic commands ###


def upgrade_engine2() -> None:
    """Upgrade engine2 schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tercero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_tercero_id'), 'tercero', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade_engine2() -> None:
    """Downgrade engine2 schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tercero_id'), table_name='tercero')
    op.drop_table('tercero')
    # ### end Alembic commands ###

