"""agregando propiedad activo a tablas

Revision ID: 56a8233da4f1
Revises: 6cd22703b025
Create Date: 2025-03-26 08:31:29.941336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a8233da4f1'
down_revision: Union[str, None] = '6cd22703b025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    """Upgrade schema."""
    # globals()["upgrade_%s" % engine_name]()
    upgrade_engine1()


def downgrade(engine_name: str) -> None:
    """Downgrade schema."""
    # globals()["downgrade_%s" % engine_name]()
    downgrade_engine1()





def upgrade_engine1() -> None:
    """Upgrade engine1 schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tercero', sa.Column('active', sa.SmallInteger(), nullable=True))
    op.add_column('usuario', sa.Column('active', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###
    op.execute('update tercero set active = 1')
    op.execute('update usuario set active = 1')
    op.execute("CREATE OR REPLACE VIEW usuario_vw AS SELECT * FROM usuario WHERE active = 1")


def downgrade_engine1() -> None:
    op.execute("DROP VIEW usuario_vw CASCADE")
    """Downgrade engine1 schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'active')
    op.drop_column('tercero', 'active')
    # ### end Alembic commands ###



def upgrade_engine2() -> None:
    """Upgrade engine2 schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tercero', sa.Column('active', sa.SmallInteger(), nullable=True))
    op.add_column('usuario', sa.Column('active', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###
    op.execute('update tercero set active = 1')
    op.execute('update usuario set active = 1')
    op.execute("CREATE OR REPLACE VIEW usuario_vw AS SELECT * FROM usuario WHERE active = 1")


def downgrade_engine2() -> None:
    op.execute("DROP VIEW usuario_vw CASCADE")
    """Downgrade engine2 schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'active')
    op.drop_column('tercero', 'active')
    # ### end Alembic commands ###

