"""ajuste representantes de tercero

Revision ID: 6cd22703b025
Revises: 0a31f4409bff
Create Date: 2025-03-26 07:34:27.296168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cd22703b025'
down_revision: Union[str, None] = '0a31f4409bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    """Upgrade schema."""
    # globals()["upgrade_%s" % engine_name]()
    upgrade_engine1()


def downgrade(engine_name: str) -> None:
    """Downgrade schema."""
    # globals()["downgrade_%s" % engine_name]()
    downgrade_engine1()




def upgrade_engine1() -> None:
    """Upgrade engine1 schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tercero', sa.Column('representative_name', sa.String(), nullable=True))
    op.add_column('tercero', sa.Column('representative_email', sa.String(), nullable=True))
    op.drop_column('tercero', 'representative')
    # ### end Alembic commands ###


def downgrade_engine1() -> None:
    """Downgrade engine1 schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tercero', sa.Column('representative', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tercero', 'representative_email')
    op.drop_column('tercero', 'representative_name')
    # ### end Alembic commands ###


def upgrade_engine2() -> None:
    """Upgrade engine2 schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tercero', sa.Column('representative_name', sa.String(), nullable=True))
    op.add_column('tercero', sa.Column('representative_email', sa.String(), nullable=True))
    op.drop_column('tercero', 'representative')
    # ### end Alembic commands ###


def downgrade_engine2() -> None:
    """Downgrade engine2 schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tercero', sa.Column('representative', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tercero', 'representative_email')
    op.drop_column('tercero', 'representative_name')
    # ### end Alembic commands ###

